CREATE TABLE IF NOT EXISTS "jihthex_dzih" ("dzih" varchar(1) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "jihthex_dzih_dzyen_tongx" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "from_dzih_id" varchar(1) NOT NULL REFERENCES "jihthex_dzih" ("dzih") DEFERRABLE INITIALLY DEFERRED, "to_dzih_id" varchar(1) NOT NULL REFERENCES "jihthex_dzih" ("dzih") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "jihthex_dzih_krau_dep" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "from_dzih_id" varchar(1) NOT NULL REFERENCES "jihthex_dzih" ("dzih") DEFERRABLE INITIALLY DEFERRED, "to_dzih_id" varchar(1) NOT NULL REFERENCES "jihthex_dzih" ("dzih") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "jihthex_dzih_krenx" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "from_dzih_id" varchar(1) NOT NULL REFERENCES "jihthex_dzih" ("dzih") DEFERRABLE INITIALLY DEFERRED, "to_dzih_id" varchar(1) NOT NULL REFERENCES "jihthex_dzih" ("dzih") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "jihthex_dzih_byan" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "from_dzih_id" varchar(1) NOT NULL REFERENCES "jihthex_dzih" ("dzih") DEFERRABLE INITIALLY DEFERRED, "to_dzih_id" varchar(1) NOT NULL REFERENCES "jihthex_dzih" ("dzih") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "jihthex_dzih_tha" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "from_dzih_id" varchar(1) NOT NULL REFERENCES "jihthex_dzih" ("dzih") DEFERRABLE INITIALLY DEFERRED, "to_dzih_id" varchar(1) NOT NULL REFERENCES "jihthex_dzih" ("dzih") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "kyonh_yonhmux" ("mjeng" varchar(3) NOT NULL PRIMARY KEY, "gheh_id" varchar(2) NOT NULL REFERENCES "kyonh_yonhgheh" ("dzih") DEFERRABLE INITIALLY DEFERRED, "tongx" smallint NOT NULL, "ho" bool NOT NULL, "tshyuk" bool NOT NULL, "tuaih_id" varchar(3) NULL UNIQUE REFERENCES "kyonh_yonhmux" ("mjeng") DEFERRABLE INITIALLY DEFERRED, "ngix_id" varchar(6) NOT NULL UNIQUE REFERENCES "kyonh_ngixqim" ("identifier") DEFERRABLE INITIALLY DEFERRED, "preng_id" varchar(6) NOT NULL UNIQUE REFERENCES "kyonh_prengqim" ("identifier") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "kyonh_prengqim" ("identifier" varchar(6) NOT NULL PRIMARY KEY, "polyhedron" varchar(12) NULL, "hiovNivv" varchar(12) NULL, "baxter" varchar(30) NULL, "tcengh" varchar(30) NULL, "putonghua" varchar(12) NULL);
CREATE TABLE IF NOT EXISTS "kyonh_kuangxyonhmiuktshiih" ("dzih" varchar(1) NOT NULL PRIMARY KEY, "kyenh" varchar(2) NOT NULL, "tshiih" smallint NOT NULL);
CREATE TABLE IF NOT EXISTS "kyonh_yonhmiuk" ("dzih" varchar(2) NOT NULL PRIMARY KEY, "gheh_id" varchar(2) NOT NULL REFERENCES "kyonh_yonhgheh" ("dzih") DEFERRABLE INITIALLY DEFERRED, "deuh" smallint NOT NULL, "tshiih_id" varchar(1) NOT NULL REFERENCES "kyonh_kuangxyonhmiuktshiih" ("dzih") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "kyonh_yonhmiuk_yonh" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "yonhmiuk_id" varchar(2) NOT NULL REFERENCES "kyonh_yonhmiuk" ("dzih") DEFERRABLE INITIALLY DEFERRED, "yonhmux_id" varchar(3) NOT NULL REFERENCES "kyonh_yonhmux" ("mjeng") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "kyonh_yonhmiukdzip" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "bieng_id" varchar(2) NULL UNIQUE REFERENCES "kyonh_yonhmiuk" ("dzih") DEFERRABLE INITIALLY DEFERRED, "dciangx_id" varchar(2) NULL UNIQUE REFERENCES "kyonh_yonhmiuk" ("dzih") DEFERRABLE INITIALLY DEFERRED, "khioh_id" varchar(2) NULL UNIQUE REFERENCES "kyonh_yonhmiuk" ("dzih") DEFERRABLE INITIALLY DEFERRED, "njip_id" varchar(2) NULL UNIQUE REFERENCES "kyonh_yonhmiuk" ("dzih") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "kyonh_yonhcjep" ("dzih" varchar(1) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "kyonh_yonhgheh" ("dzih" varchar(2) NOT NULL PRIMARY KEY, "cjep_id" varchar(1) NOT NULL REFERENCES "kyonh_yonhcjep" ("dzih") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "kyonh_dciangxdzih" ("dzih" varchar(1) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "kyonh_dciangxdzih_cjeng" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "dciangxdzih_id" varchar(1) NOT NULL REFERENCES "kyonh_dciangxdzih" ("dzih") DEFERRABLE INITIALLY DEFERRED, "cjengmux_id" varchar(1) NOT NULL REFERENCES "kyonh_cjengmux" ("dzih") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "kyonh_ghraxdzih" ("dzih" varchar(1) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "kyonh_ghraxdzih_yonh" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "ghraxdzih_id" varchar(1) NOT NULL REFERENCES "kyonh_ghraxdzih" ("dzih") DEFERRABLE INITIALLY DEFERRED, "yonhmux_id" varchar(3) NOT NULL REFERENCES "kyonh_yonhmux" ("mjeng") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "kyonh_pyanxtshet" ("tshet" varchar(2) NOT NULL PRIMARY KEY, "dciangx_id" varchar(1) NOT NULL REFERENCES "kyonh_dciangxdzih" ("dzih") DEFERRABLE INITIALLY DEFERRED, "ghrax_id" varchar(1) NOT NULL REFERENCES "kyonh_ghraxdzih" ("dzih") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "kyonh_ngixqim" ("identifier" varchar(6) NOT NULL PRIMARY KEY, "kauPuonxHanh" varchar(16) NULL, "lixPyangKueh" varchar(16) NULL, "yangLik" varchar(16) NULL, "tciuPyapKau" varchar(16) NULL, "liukTcihYoi" varchar(16) NULL, "tungxDungGhua" varchar(16) NULL, "lixYeng" varchar(16) NULL, "dcjeuhYengPhyon" varchar(16) NULL, "drienghTriangDciangPyang" varchar(16) NULL, "phuanNgohYon" varchar(16) NULL, "boLipPuonx" varchar(16) NULL);
CREATE TABLE IF NOT EXISTS "kyonh_dzih" ("ziox" integer NOT NULL PRIMARY KEY, "dzih" varchar(1) NOT NULL, "sieuxYonh_id" integer NOT NULL REFERENCES "kyonh_sieuxyonh" ("ziox") DEFERRABLE INITIALLY DEFERRED, "yih" integer NOT NULL, "ngieh" text NOT NULL);
CREATE TABLE IF NOT EXISTS "kyonh_cjenglyih" ("mjeng" varchar(5) NOT NULL PRIMARY KEY, "ziox" integer NOT NULL);
CREATE TABLE IF NOT EXISTS "kyonh_cjengmux" ("dzih" varchar(1) NOT NULL PRIMARY KEY, "lyih_id" varchar(5) NOT NULL REFERENCES "kyonh_cjenglyih" ("mjeng") DEFERRABLE INITIALLY DEFERRED, "ngix_id" varchar(6) NOT NULL UNIQUE REFERENCES "kyonh_ngixqim" ("identifier") DEFERRABLE INITIALLY DEFERRED, "preng_id" varchar(6) NOT NULL UNIQUE REFERENCES "kyonh_prengqim" ("identifier") DEFERRABLE INITIALLY DEFERRED, "ziox" integer NOT NULL);
CREATE TABLE IF NOT EXISTS "kyonh_drakdzuondang" ("identifier" varchar(4) NOT NULL PRIMARY KEY, "kyenh" smallint NOT NULL, "jep" smallint NOT NULL, "myon" text NOT NULL);
CREATE TABLE IF NOT EXISTS "kyonh_cio" ("identifier" varchar(4) NOT NULL PRIMARY KEY, "drakDzuonDang_id" varchar(4) NOT NULL UNIQUE REFERENCES "kyonh_drakdzuondang" ("identifier") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "kyonh_sieuxyonh" ("ziox" integer NOT NULL PRIMARY KEY, "taj" varchar(1) NOT NULL, "cjeng_id" varchar(1) NOT NULL REFERENCES "kyonh_cjengmux" ("dzih") DEFERRABLE INITIALLY DEFERRED, "yonh_id" varchar(3) NOT NULL REFERENCES "kyonh_yonhmux" ("mjeng") DEFERRABLE INITIALLY DEFERRED, "yonhMiuk_id" varchar(2) NOT NULL REFERENCES "kyonh_yonhmiuk" ("dzih") DEFERRABLE INITIALLY DEFERRED, "pyanx_id" varchar(2) NULL REFERENCES "kyonh_pyanxtshet" ("tshet") DEFERRABLE INITIALLY DEFERRED, "ngix_id" varchar(6) NOT NULL UNIQUE REFERENCES "kyonh_ngixqim" ("identifier") DEFERRABLE INITIALLY DEFERRED, "preng_id" varchar(6) NOT NULL UNIQUE REFERENCES "kyonh_prengqim" ("identifier") DEFERRABLE INITIALLY DEFERRED, "dauh_id" varchar(6) NOT NULL UNIQUE REFERENCES "kyonh_prengqim" ("identifier") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "kyonh_sieuxyonh_cio" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "sieuxyonh_id" integer NOT NULL REFERENCES "kyonh_sieuxyonh" ("ziox") DEFERRABLE INITIALLY DEFERRED, "cio_id" varchar(4) NOT NULL REFERENCES "kyonh_cio" ("identifier") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "tcenghyonhtsen_cio" ("identifier" varchar(5) NOT NULL PRIMARY KEY, "kyenh" smallint NOT NULL, "jep" smallint NOT NULL);
CREATE TABLE IF NOT EXISTS "tcenghyonhtsen_dzih" ("ziox" integer NOT NULL PRIMARY KEY, "dzih" varchar(1) NOT NULL, "sieux_id" integer NOT NULL REFERENCES "tcenghyonhtsen_sieuxyonh" ("ziox") DEFERRABLE INITIALLY DEFERRED, "ngieh" text NOT NULL, "kwangx_id" integer NULL REFERENCES "kyonh_sieuxyonh" ("ziox") DEFERRABLE INITIALLY DEFERRED, "cioTriungZiox" integer NOT NULL);
CREATE TABLE IF NOT EXISTS "tcenghyonhtsen_dzih_cio" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "dzih_id" integer NOT NULL REFERENCES "tcenghyonhtsen_dzih" ("ziox") DEFERRABLE INITIALLY DEFERRED, "cio_id" varchar(5) NOT NULL REFERENCES "tcenghyonhtsen_cio" ("identifier") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "tcenghyonhtsen_koxqim" ("ziox" integer NOT NULL PRIMARY KEY, "dzih" varchar(1) NOT NULL, "sieux_id" integer NOT NULL REFERENCES "tcenghyonhtsen_sieuxyonh" ("ziox") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "tcenghyonhtsen_koxqim_cio" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "koxqim_id" integer NOT NULL REFERENCES "tcenghyonhtsen_koxqim" ("ziox") DEFERRABLE INITIALLY DEFERRED, "cio_id" varchar(5) NOT NULL REFERENCES "tcenghyonhtsen_cio" ("identifier") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "tcenghyonhtsen_jitdzih" ("ziox" integer NOT NULL PRIMARY KEY, "dzih" varchar(1) NOT NULL, "sieux_id" integer NOT NULL REFERENCES "tcenghyonhtsen_sieuxyonh" ("ziox") DEFERRABLE INITIALLY DEFERRED, "ngieh" text NOT NULL, "kwangx_id" integer NULL REFERENCES "kyonh_sieuxyonh" ("ziox") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "tcenghyonhtsen_jitdzih_cio" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "jitdzih_id" integer NOT NULL REFERENCES "tcenghyonhtsen_jitdzih" ("ziox") DEFERRABLE INITIALLY DEFERRED, "cio_id" varchar(5) NOT NULL REFERENCES "tcenghyonhtsen_cio" ("identifier") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "tcenghyonhtsen_dciangxdzih" ("dzih" varchar(1) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "tcenghyonhtsen_ghraxdzih" ("dzih" varchar(1) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "tcenghyonhtsen_pyanxtshet" ("tshet" varchar(2) NOT NULL PRIMARY KEY, "dciangx_id" varchar(1) NOT NULL REFERENCES "tcenghyonhtsen_dciangxdzih" ("dzih") DEFERRABLE INITIALLY DEFERRED, "ghrax_id" varchar(1) NOT NULL REFERENCES "tcenghyonhtsen_ghraxdzih" ("dzih") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "tcenghyonhtsen_qimbjin" ("ziox" integer NOT NULL PRIMARY KEY, "t1_id" integer NULL REFERENCES "tcenghyonhtsen_sieuxyonh" ("ziox") DEFERRABLE INITIALLY DEFERRED, "t2_id" integer NULL REFERENCES "tcenghyonhtsen_sieuxyonh" ("ziox") DEFERRABLE INITIALLY DEFERRED, "t3_id" integer NULL REFERENCES "tcenghyonhtsen_sieuxyonh" ("ziox") DEFERRABLE INITIALLY DEFERRED, "t4_id" integer NULL REFERENCES "tcenghyonhtsen_sieuxyonh" ("ziox") DEFERRABLE INITIALLY DEFERRED, "merge_t2_t3" bool NOT NULL, "has_t4" bool NOT NULL, "filename" varchar(16) NOT NULL, "additional_id" integer NULL REFERENCES "tcenghyonhtsen_sieuxyonh" ("ziox") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "tcenghyonhtsen_sieuxyonh" ("ziox" integer NOT NULL PRIMARY KEY, "taj" varchar(1) NOT NULL, "yonhMiuk_id" varchar(2) NOT NULL REFERENCES "tcenghyonhtsen_yonhmiuk" ("dzih") DEFERRABLE INITIALLY DEFERRED, "pyanx_id" varchar(2) NULL REFERENCES "tcenghyonhtsen_pyanxtshet" ("tshet") DEFERRABLE INITIALLY DEFERRED, "jamo" varchar(16) NOT NULL, "ipa" varchar(16) NOT NULL, "cioTriungZiox" integer NOT NULL);
CREATE TABLE IF NOT EXISTS "tcenghyonhtsen_sieuxyonh_cio" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "sieuxyonh_id" integer NOT NULL REFERENCES "tcenghyonhtsen_sieuxyonh" ("ziox") DEFERRABLE INITIALLY DEFERRED, "cio_id" varchar(5) NOT NULL REFERENCES "tcenghyonhtsen_cio" ("identifier") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "tcenghyonhtsen_ghiunhtranscription" ("ziox" integer NOT NULL PRIMARY KEY, "ghiunhBox" varchar(4) NOT NULL, "shioJiekHiunh" varchar(8) NOT NULL, "shioIpa" varchar(16) NOT NULL, "njipJiekHiunh" varchar(8) NOT NULL, "njipIpa" varchar(16) NOT NULL);
CREATE TABLE IF NOT EXISTS "tcenghyonhtsen_shiengtranscription" ("ziox" integer NOT NULL PRIMARY KEY, "shiengLwih" varchar(4) NOT NULL, "jiekHiunh" varchar(8) NOT NULL, "ipa" varchar(16) NOT NULL, "memo" text NOT NULL);
CREATE TABLE IF NOT EXISTS "tcenghyonhtsen_dewhtranscription" ("ziox" integer NOT NULL PRIMARY KEY, "dewhLwih" varchar(4) NOT NULL, "jiekHiunh" varchar(8) NOT NULL, "ipa" varchar(16) NOT NULL, "memo" text NOT NULL);
CREATE TABLE IF NOT EXISTS "tcenghyonhtsen_yonhbux" ("ziox" integer NOT NULL PRIMARY KEY, "dzih" varchar(2) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "tcenghyonhtsen_yonhmiuk" ("ziox" integer NOT NULL, "dzih" varchar(2) NOT NULL PRIMARY KEY, "bux_id" integer NOT NULL REFERENCES "tcenghyonhtsen_yonhbux" ("ziox") DEFERRABLE INITIALLY DEFERRED, "deuh" smallint NOT NULL);
CREATE TABLE IF NOT EXISTS "pyonh_cio" ("identifier" varchar(5) NOT NULL PRIMARY KEY, "kyenh" smallint NOT NULL, "jep" smallint NOT NULL);
CREATE TABLE IF NOT EXISTS "pyonh_cjenglyih" ("mjeng" varchar(5) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "pyonh_cjengmux" ("dzih" varchar(1) NOT NULL PRIMARY KEY, "lyih_id" varchar(5) NOT NULL REFERENCES "pyonh_cjenglyih" ("mjeng") DEFERRABLE INITIALLY DEFERRED, "ngix_id" varchar(6) NOT NULL UNIQUE REFERENCES "pyonh_ngixqim" ("identifier") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "pyonh_dzih" ("ziox" integer NOT NULL PRIMARY KEY, "dzih" varchar(1) NOT NULL, "sieux_yonh_id" integer NOT NULL REFERENCES "pyonh_sieuxyonh" ("ziox") DEFERRABLE INITIALLY DEFERRED, "ngieh" text NOT NULL);
CREATE TABLE IF NOT EXISTS "pyonh_dzih_cio" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "dzih_id" integer NOT NULL REFERENCES "pyonh_dzih" ("ziox") DEFERRABLE INITIALLY DEFERRED, "cio_id" varchar(5) NOT NULL REFERENCES "pyonh_cio" ("identifier") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "pyonh_ngixqim" ("identifier" varchar(6) NOT NULL PRIMARY KEY, "triang_gyon_henx" varchar(16) NULL);
CREATE TABLE IF NOT EXISTS "pyonh_yonhbox" ("ziox" integer NOT NULL PRIMARY KEY, "mjeng" varchar(4) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "pyonh_yonhmux" ("mjeng" varchar(3) NOT NULL PRIMARY KEY, "yonh_box_id" integer NOT NULL REFERENCES "pyonh_yonhbox" ("ziox") DEFERRABLE INITIALLY DEFERRED, "tshyuk" bool NOT NULL, "tuaih_id" varchar(3) NULL REFERENCES "pyonh_yonhmux" ("mjeng") DEFERRABLE INITIALLY DEFERRED, "ngix_id" varchar(6) NOT NULL UNIQUE REFERENCES "pyonh_ngixqim" ("identifier") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "pyonh_sieuxyonh" ("ziox" integer NOT NULL PRIMARY KEY, "taj" varchar(1) NOT NULL, "cjeng_id" varchar(1) NOT NULL REFERENCES "pyonh_cjengmux" ("dzih") DEFERRABLE INITIALLY DEFERRED, "yonh_box_id" integer NOT NULL REFERENCES "pyonh_yonhbox" ("ziox") DEFERRABLE INITIALLY DEFERRED, "yonh_id" varchar(3) NOT NULL REFERENCES "pyonh_yonhmux" ("mjeng") DEFERRABLE INITIALLY DEFERRED, "qim_jang" bool NOT NULL, "deuh" integer NOT NULL);
CREATE TABLE IF NOT EXISTS "pyonh_sieuxyonh_cio" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "sieuxyonh_id" integer NOT NULL REFERENCES "pyonh_sieuxyonh" ("ziox") DEFERRABLE INITIALLY DEFERRED, "cio_id" varchar(5) NOT NULL REFERENCES "pyonh_cio" ("identifier") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "trngyan_cio" ("identifier" varchar(5) NOT NULL PRIMARY KEY, "kyenh" smallint NOT NULL, "jep" smallint NOT NULL);
CREATE TABLE IF NOT EXISTS "trngyan_cjenglyih" ("mjeng" varchar(2) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "trngyan_cjengmux" ("dzih" varchar(1) NOT NULL PRIMARY KEY, "lyih_id" varchar(2) NOT NULL REFERENCES "trngyan_cjenglyih" ("mjeng") DEFERRABLE INITIALLY DEFERRED, "ngix_id" varchar(6) NOT NULL UNIQUE REFERENCES "trngyan_ngixqim" ("identifier") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "trngyan_dzih" ("ziox" integer NOT NULL PRIMARY KEY, "id" varchar(2) NOT NULL, "dzih" varchar(1) NOT NULL, "sieux_yonh_id" integer NOT NULL REFERENCES "trngyan_sieuxyonh" ("ziox") DEFERRABLE INITIALLY DEFERRED, "tryoh" text NOT NULL);
CREATE TABLE IF NOT EXISTS "trngyan_dzih_cio" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "dzih_id" integer NOT NULL REFERENCES "trngyan_dzih" ("ziox") DEFERRABLE INITIALLY DEFERRED, "cio_id" varchar(5) NOT NULL REFERENCES "trngyan_cio" ("identifier") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "trngyan_ngixqim" ("identifier" varchar(6) NOT NULL PRIMARY KEY, "neng_keh_piuk" varchar(16) NULL);
CREATE TABLE IF NOT EXISTS "trngyan_sieuxyonh" ("ziox" integer NOT NULL PRIMARY KEY, "taj" varchar(1) NOT NULL, "cjeng_id" varchar(1) NOT NULL REFERENCES "trngyan_cjengmux" ("dzih") DEFERRABLE INITIALLY DEFERRED, "yonh_box_id" varchar(2) NOT NULL REFERENCES "trngyan_yonhbox" ("mjeng") DEFERRABLE INITIALLY DEFERRED, "yonh_id" varchar(4) NOT NULL REFERENCES "trngyan_yonhmux" ("mjeng") DEFERRABLE INITIALLY DEFERRED, "deuh" integer NOT NULL, "ho" integer NOT NULL);
CREATE TABLE IF NOT EXISTS "trngyan_sieuxyonh_cio" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "sieuxyonh_id" integer NOT NULL REFERENCES "trngyan_sieuxyonh" ("ziox") DEFERRABLE INITIALLY DEFERRED, "cio_id" varchar(5) NOT NULL REFERENCES "trngyan_cio" ("identifier") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "trngyan_yonhbox" ("mjeng" varchar(2) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "trngyan_yonhmux" ("mjeng" varchar(4) NOT NULL PRIMARY KEY, "yonh_box_id" varchar(2) NOT NULL REFERENCES "trngyan_yonhbox" ("mjeng") DEFERRABLE INITIALLY DEFERRED, "ho" integer NOT NULL, "ngix_id" varchar(6) NOT NULL UNIQUE REFERENCES "trngyan_ngixqim" ("identifier") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "dciangxkox_cjengbyo" ("mjeng" varchar(1) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "dciangxkox_yonhbox" ("mjeng" varchar(1) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "dciangxkox_dzih" ("ziox" integer NOT NULL PRIMARY KEY, "id" varchar(2) NOT NULL, "dzih" varchar(1) NOT NULL, "sieux_yonh_id" integer NULL REFERENCES "kyonh_sieuxyonh" ("ziox") DEFERRABLE INITIALLY DEFERRED, "cjeng_id" varchar(1) NOT NULL REFERENCES "dciangxkox_cjengbyo" ("mjeng") DEFERRABLE INITIALLY DEFERRED, "yonh_id" varchar(1) NOT NULL REFERENCES "dciangxkox_yonhbox" ("mjeng") DEFERRABLE INITIALLY DEFERRED, "yonh_seh" integer NOT NULL, "ngix_1" varchar(16) NOT NULL, "ngix_2" varchar(16) NOT NULL, "ngix_3" varchar(16) NOT NULL, "tryoh" text NOT NULL);
CREATE UNIQUE INDEX "jihthex_dzih_dzyen_tongx_from_dzih_id_to_dzih_id_323cfbae_uniq" ON "jihthex_dzih_dzyen_tongx" ("from_dzih_id", "to_dzih_id");
CREATE INDEX "jihthex_dzih_dzyen_tongx_from_dzih_id_0cff7019" ON "jihthex_dzih_dzyen_tongx" ("from_dzih_id");
CREATE INDEX "jihthex_dzih_dzyen_tongx_to_dzih_id_25489977" ON "jihthex_dzih_dzyen_tongx" ("to_dzih_id");
CREATE UNIQUE INDEX "jihthex_dzih_krau_dep_from_dzih_id_to_dzih_id_3169a6ef_uniq" ON "jihthex_dzih_krau_dep" ("from_dzih_id", "to_dzih_id");
CREATE INDEX "jihthex_dzih_krau_dep_from_dzih_id_d4f91bb6" ON "jihthex_dzih_krau_dep" ("from_dzih_id");
CREATE INDEX "jihthex_dzih_krau_dep_to_dzih_id_f2ee5ee3" ON "jihthex_dzih_krau_dep" ("to_dzih_id");
CREATE UNIQUE INDEX "jihthex_dzih_krenx_from_dzih_id_to_dzih_id_495c2aa4_uniq" ON "jihthex_dzih_krenx" ("from_dzih_id", "to_dzih_id");
CREATE INDEX "jihthex_dzih_krenx_from_dzih_id_172fa2a2" ON "jihthex_dzih_krenx" ("from_dzih_id");
CREATE INDEX "jihthex_dzih_krenx_to_dzih_id_39def383" ON "jihthex_dzih_krenx" ("to_dzih_id");
CREATE UNIQUE INDEX "jihthex_dzih_byan_from_dzih_id_to_dzih_id_6e0e5121_uniq" ON "jihthex_dzih_byan" ("from_dzih_id", "to_dzih_id");
CREATE INDEX "jihthex_dzih_byan_from_dzih_id_cc37d6ef" ON "jihthex_dzih_byan" ("from_dzih_id");
CREATE INDEX "jihthex_dzih_byan_to_dzih_id_186b8340" ON "jihthex_dzih_byan" ("to_dzih_id");
CREATE UNIQUE INDEX "jihthex_dzih_tha_from_dzih_id_to_dzih_id_b30efeee_uniq" ON "jihthex_dzih_tha" ("from_dzih_id", "to_dzih_id");
CREATE INDEX "jihthex_dzih_tha_from_dzih_id_cbfe14cd" ON "jihthex_dzih_tha" ("from_dzih_id");
CREATE INDEX "jihthex_dzih_tha_to_dzih_id_dfbaef5e" ON "jihthex_dzih_tha" ("to_dzih_id");
CREATE INDEX "kyonh_yonhmux_gheh_id_265e6bfe" ON "kyonh_yonhmux" ("gheh_id");
CREATE INDEX "kyonh_yonhmux_tongx_b20812cb" ON "kyonh_yonhmux" ("tongx");
CREATE INDEX "kyonh_yonhmux_ho_1b0ecfda" ON "kyonh_yonhmux" ("ho");
CREATE INDEX "kyonh_yonhmux_tshyuk_6594d257" ON "kyonh_yonhmux" ("tshyuk");
CREATE INDEX "kyonh_yonhmiuk_gheh_id_11c2b540" ON "kyonh_yonhmiuk" ("gheh_id");
CREATE INDEX "kyonh_yonhmiuk_tshiih_id_0cca16c7" ON "kyonh_yonhmiuk" ("tshiih_id");
CREATE UNIQUE INDEX "kyonh_yonhmiuk_yonh_yonhmiuk_id_yonhmux_id_b6bc7455_uniq" ON "kyonh_yonhmiuk_yonh" ("yonhmiuk_id", "yonhmux_id");
CREATE INDEX "kyonh_yonhmiuk_yonh_yonhmiuk_id_ed6975c5" ON "kyonh_yonhmiuk_yonh" ("yonhmiuk_id");
CREATE INDEX "kyonh_yonhmiuk_yonh_yonhmux_id_95d894f3" ON "kyonh_yonhmiuk_yonh" ("yonhmux_id");
CREATE INDEX "kyonh_yonhgheh_cjep_id_91af1d31" ON "kyonh_yonhgheh" ("cjep_id");
CREATE UNIQUE INDEX "kyonh_dciangxdzih_cjeng_dciangxdzih_id_cjengmux_id_312cc5ed_uniq" ON "kyonh_dciangxdzih_cjeng" ("dciangxdzih_id", "cjengmux_id");
CREATE INDEX "kyonh_dciangxdzih_cjeng_dciangxdzih_id_2418fbed" ON "kyonh_dciangxdzih_cjeng" ("dciangxdzih_id");
CREATE INDEX "kyonh_dciangxdzih_cjeng_cjengmux_id_c95be45b" ON "kyonh_dciangxdzih_cjeng" ("cjengmux_id");
CREATE UNIQUE INDEX "kyonh_ghraxdzih_yonh_ghraxdzih_id_yonhmux_id_1809715e_uniq" ON "kyonh_ghraxdzih_yonh" ("ghraxdzih_id", "yonhmux_id");
CREATE INDEX "kyonh_ghraxdzih_yonh_ghraxdzih_id_024980c3" ON "kyonh_ghraxdzih_yonh" ("ghraxdzih_id");
CREATE INDEX "kyonh_ghraxdzih_yonh_yonhmux_id_84576113" ON "kyonh_ghraxdzih_yonh" ("yonhmux_id");
CREATE INDEX "kyonh_pyanxtshet_dciangx_id_793e060a" ON "kyonh_pyanxtshet" ("dciangx_id");
CREATE INDEX "kyonh_pyanxtshet_ghrax_id_15b6d792" ON "kyonh_pyanxtshet" ("ghrax_id");
CREATE INDEX "kyonh_dzih_dzih_238aa6f9" ON "kyonh_dzih" ("dzih");
CREATE INDEX "kyonh_dzih_sieuxYonh_id_f252bfcf" ON "kyonh_dzih" ("sieuxYonh_id");
CREATE INDEX "kyonh_dzih_yih_470f292d" ON "kyonh_dzih" ("yih");
CREATE INDEX "kyonh_cjengmux_lyih_id_9d66785d" ON "kyonh_cjengmux" ("lyih_id");
CREATE INDEX "kyonh_drakdzuondang_kyenh_29f781e4" ON "kyonh_drakdzuondang" ("kyenh");
CREATE INDEX "kyonh_drakdzuondang_jep_904cd0a9" ON "kyonh_drakdzuondang" ("jep");
CREATE INDEX "kyonh_sieuxyonh_taj_44672b97" ON "kyonh_sieuxyonh" ("taj");
CREATE INDEX "kyonh_sieuxyonh_cjeng_id_7ed444d1" ON "kyonh_sieuxyonh" ("cjeng_id");
CREATE INDEX "kyonh_sieuxyonh_yonh_id_d82104e1" ON "kyonh_sieuxyonh" ("yonh_id");
CREATE INDEX "kyonh_sieuxyonh_yonhMiuk_id_466ab665" ON "kyonh_sieuxyonh" ("yonhMiuk_id");
CREATE INDEX "kyonh_sieuxyonh_pyanx_id_2d29a13d" ON "kyonh_sieuxyonh" ("pyanx_id");
CREATE UNIQUE INDEX "kyonh_sieuxyonh_cio_sieuxyonh_id_cio_id_44561e8f_uniq" ON "kyonh_sieuxyonh_cio" ("sieuxyonh_id", "cio_id");
CREATE INDEX "kyonh_sieuxyonh_cio_sieuxyonh_id_e3a5f152" ON "kyonh_sieuxyonh_cio" ("sieuxyonh_id");
CREATE INDEX "kyonh_sieuxyonh_cio_cio_id_2453950e" ON "kyonh_sieuxyonh_cio" ("cio_id");
CREATE INDEX "tcenghyonhtsen_cio_kyenh_4dac520b" ON "tcenghyonhtsen_cio" ("kyenh");
CREATE INDEX "tcenghyonhtsen_cio_jep_8017350e" ON "tcenghyonhtsen_cio" ("jep");
CREATE INDEX "tcenghyonhtsen_dzih_dzih_bfec92d1" ON "tcenghyonhtsen_dzih" ("dzih");
CREATE INDEX "tcenghyonhtsen_dzih_sieux_id_376faba4" ON "tcenghyonhtsen_dzih" ("sieux_id");
CREATE INDEX "tcenghyonhtsen_dzih_kwangx_id_a89e936b" ON "tcenghyonhtsen_dzih" ("kwangx_id");
CREATE INDEX "tcenghyonhtsen_dzih_cioTriungZiox_eaa44934" ON "tcenghyonhtsen_dzih" ("cioTriungZiox");
CREATE UNIQUE INDEX "tcenghyonhtsen_dzih_cio_dzih_id_cio_id_c6d5da59_uniq" ON "tcenghyonhtsen_dzih_cio" ("dzih_id", "cio_id");
CREATE INDEX "tcenghyonhtsen_dzih_cio_dzih_id_41cf6c3c" ON "tcenghyonhtsen_dzih_cio" ("dzih_id");
CREATE INDEX "tcenghyonhtsen_dzih_cio_cio_id_02990736" ON "tcenghyonhtsen_dzih_cio" ("cio_id");
CREATE INDEX "tcenghyonhtsen_koxqim_dzih_abfaff9e" ON "tcenghyonhtsen_koxqim" ("dzih");
CREATE INDEX "tcenghyonhtsen_koxqim_sieux_id_04788c21" ON "tcenghyonhtsen_koxqim" ("sieux_id");
CREATE UNIQUE INDEX "tcenghyonhtsen_koxqim_cio_koxqim_id_cio_id_7c8a44ee_uniq" ON "tcenghyonhtsen_koxqim_cio" ("koxqim_id", "cio_id");
CREATE INDEX "tcenghyonhtsen_koxqim_cio_koxqim_id_92b2f9a4" ON "tcenghyonhtsen_koxqim_cio" ("koxqim_id");
CREATE INDEX "tcenghyonhtsen_koxqim_cio_cio_id_2c595689" ON "tcenghyonhtsen_koxqim_cio" ("cio_id");
CREATE INDEX "tcenghyonhtsen_jitdzih_dzih_7816e327" ON "tcenghyonhtsen_jitdzih" ("dzih");
CREATE INDEX "tcenghyonhtsen_jitdzih_sieux_id_698c768e" ON "tcenghyonhtsen_jitdzih" ("sieux_id");
CREATE INDEX "tcenghyonhtsen_jitdzih_kwangx_id_b02e8284" ON "tcenghyonhtsen_jitdzih" ("kwangx_id");
CREATE UNIQUE INDEX "tcenghyonhtsen_jitdzih_cio_jitdzih_id_cio_id_ef18bf4b_uniq" ON "tcenghyonhtsen_jitdzih_cio" ("jitdzih_id", "cio_id");
CREATE INDEX "tcenghyonhtsen_jitdzih_cio_jitdzih_id_101100b8" ON "tcenghyonhtsen_jitdzih_cio" ("jitdzih_id");
CREATE INDEX "tcenghyonhtsen_jitdzih_cio_cio_id_835e25b7" ON "tcenghyonhtsen_jitdzih_cio" ("cio_id");
CREATE INDEX "tcenghyonhtsen_pyanxtshet_dciangx_id_76db25ae" ON "tcenghyonhtsen_pyanxtshet" ("dciangx_id");
CREATE INDEX "tcenghyonhtsen_pyanxtshet_ghrax_id_ad015f2a" ON "tcenghyonhtsen_pyanxtshet" ("ghrax_id");
CREATE INDEX "tcenghyonhtsen_qimbjin_t1_id_fcd3b89c" ON "tcenghyonhtsen_qimbjin" ("t1_id");
CREATE INDEX "tcenghyonhtsen_qimbjin_t2_id_40b9a1f4" ON "tcenghyonhtsen_qimbjin" ("t2_id");
CREATE INDEX "tcenghyonhtsen_qimbjin_t3_id_0c1a1418" ON "tcenghyonhtsen_qimbjin" ("t3_id");
CREATE INDEX "tcenghyonhtsen_qimbjin_t4_id_db7337c1" ON "tcenghyonhtsen_qimbjin" ("t4_id");
CREATE INDEX "tcenghyonhtsen_qimbjin_filename_8d65697e" ON "tcenghyonhtsen_qimbjin" ("filename");
CREATE INDEX "tcenghyonhtsen_qimbjin_additional_id_891bfbea" ON "tcenghyonhtsen_qimbjin" ("additional_id");
CREATE INDEX "tcenghyonhtsen_sieuxyonh_taj_ae06cc3b" ON "tcenghyonhtsen_sieuxyonh" ("taj");
CREATE INDEX "tcenghyonhtsen_sieuxyonh_yonhMiuk_id_2cb12b9e" ON "tcenghyonhtsen_sieuxyonh" ("yonhMiuk_id");
CREATE INDEX "tcenghyonhtsen_sieuxyonh_pyanx_id_7de068af" ON "tcenghyonhtsen_sieuxyonh" ("pyanx_id");
CREATE INDEX "tcenghyonhtsen_sieuxyonh_jamo_e629097f" ON "tcenghyonhtsen_sieuxyonh" ("jamo");
CREATE INDEX "tcenghyonhtsen_sieuxyonh_ipa_83a0966a" ON "tcenghyonhtsen_sieuxyonh" ("ipa");
CREATE INDEX "tcenghyonhtsen_sieuxyonh_cioTriungZiox_2df8e62a" ON "tcenghyonhtsen_sieuxyonh" ("cioTriungZiox");
CREATE UNIQUE INDEX "tcenghyonhtsen_sieuxyonh_cio_sieuxyonh_id_cio_id_e3e135fd_uniq" ON "tcenghyonhtsen_sieuxyonh_cio" ("sieuxyonh_id", "cio_id");
CREATE INDEX "tcenghyonhtsen_sieuxyonh_cio_sieuxyonh_id_f66d37d8" ON "tcenghyonhtsen_sieuxyonh_cio" ("sieuxyonh_id");
CREATE INDEX "tcenghyonhtsen_sieuxyonh_cio_cio_id_16eb3cc2" ON "tcenghyonhtsen_sieuxyonh_cio" ("cio_id");
CREATE INDEX "tcenghyonhtsen_yonhmiuk_bux_id_8d797fd6" ON "tcenghyonhtsen_yonhmiuk" ("bux_id");
CREATE INDEX "pyonh_cio_kyenh_e893e6f8" ON "pyonh_cio" ("kyenh");
CREATE INDEX "pyonh_cio_jep_9e4dfbc5" ON "pyonh_cio" ("jep");
CREATE INDEX "pyonh_cjengmux_lyih_id_f65a9d45" ON "pyonh_cjengmux" ("lyih_id");
CREATE INDEX "pyonh_dzih_dzih_22773c60" ON "pyonh_dzih" ("dzih");
CREATE INDEX "pyonh_dzih_sieux_yonh_id_028ee2a0" ON "pyonh_dzih" ("sieux_yonh_id");
CREATE UNIQUE INDEX "pyonh_dzih_cio_dzih_id_cio_id_a6a8869e_uniq" ON "pyonh_dzih_cio" ("dzih_id", "cio_id");
CREATE INDEX "pyonh_dzih_cio_dzih_id_5107b98f" ON "pyonh_dzih_cio" ("dzih_id");
CREATE INDEX "pyonh_dzih_cio_cio_id_49d003d9" ON "pyonh_dzih_cio" ("cio_id");
CREATE INDEX "pyonh_yonhmux_yonh_box_id_262af196" ON "pyonh_yonhmux" ("yonh_box_id");
CREATE INDEX "pyonh_yonhmux_tuaih_id_8e3b254b" ON "pyonh_yonhmux" ("tuaih_id");
CREATE INDEX "pyonh_sieuxyonh_taj_5685086b" ON "pyonh_sieuxyonh" ("taj");
CREATE INDEX "pyonh_sieuxyonh_cjeng_id_676b1c95" ON "pyonh_sieuxyonh" ("cjeng_id");
CREATE INDEX "pyonh_sieuxyonh_yonh_box_id_604548f8" ON "pyonh_sieuxyonh" ("yonh_box_id");
CREATE INDEX "pyonh_sieuxyonh_yonh_id_8d8e9841" ON "pyonh_sieuxyonh" ("yonh_id");
CREATE UNIQUE INDEX "pyonh_sieuxyonh_cio_sieuxyonh_id_cio_id_50bbb530_uniq" ON "pyonh_sieuxyonh_cio" ("sieuxyonh_id", "cio_id");
CREATE INDEX "pyonh_sieuxyonh_cio_sieuxyonh_id_929bb1c3" ON "pyonh_sieuxyonh_cio" ("sieuxyonh_id");
CREATE INDEX "pyonh_sieuxyonh_cio_cio_id_ecfe85cd" ON "pyonh_sieuxyonh_cio" ("cio_id");
CREATE INDEX "trngyan_cio_kyenh_20419568" ON "trngyan_cio" ("kyenh");
CREATE INDEX "trngyan_cio_jep_61270406" ON "trngyan_cio" ("jep");
CREATE INDEX "trngyan_cjengmux_lyih_id_2ad38924" ON "trngyan_cjengmux" ("lyih_id");
CREATE INDEX "trngyan_dzih_id_9847a434" ON "trngyan_dzih" ("id");
CREATE INDEX "trngyan_dzih_dzih_6fc0ad3c" ON "trngyan_dzih" ("dzih");
CREATE INDEX "trngyan_dzih_sieux_yonh_id_991e54fa" ON "trngyan_dzih" ("sieux_yonh_id");
CREATE UNIQUE INDEX "trngyan_dzih_cio_dzih_id_cio_id_20b5f05d_uniq" ON "trngyan_dzih_cio" ("dzih_id", "cio_id");
CREATE INDEX "trngyan_dzih_cio_dzih_id_259533a9" ON "trngyan_dzih_cio" ("dzih_id");
CREATE INDEX "trngyan_dzih_cio_cio_id_49828d45" ON "trngyan_dzih_cio" ("cio_id");
CREATE INDEX "trngyan_sieuxyonh_taj_707d0171" ON "trngyan_sieuxyonh" ("taj");
CREATE INDEX "trngyan_sieuxyonh_cjeng_id_41d4ea30" ON "trngyan_sieuxyonh" ("cjeng_id");
CREATE INDEX "trngyan_sieuxyonh_yonh_box_id_3473c5aa" ON "trngyan_sieuxyonh" ("yonh_box_id");
CREATE INDEX "trngyan_sieuxyonh_yonh_id_3241fad7" ON "trngyan_sieuxyonh" ("yonh_id");
CREATE UNIQUE INDEX "trngyan_sieuxyonh_cio_sieuxyonh_id_cio_id_c3ce7930_uniq" ON "trngyan_sieuxyonh_cio" ("sieuxyonh_id", "cio_id");
CREATE INDEX "trngyan_sieuxyonh_cio_sieuxyonh_id_bce12e94" ON "trngyan_sieuxyonh_cio" ("sieuxyonh_id");
CREATE INDEX "trngyan_sieuxyonh_cio_cio_id_1d442fcb" ON "trngyan_sieuxyonh_cio" ("cio_id");
CREATE INDEX "trngyan_yonhmux_yonh_box_id_dedb2235" ON "trngyan_yonhmux" ("yonh_box_id");
CREATE INDEX "dciangxkox_dzih_id_fd335b75" ON "dciangxkox_dzih" ("id");
CREATE INDEX "dciangxkox_dzih_dzih_55c6dcea" ON "dciangxkox_dzih" ("dzih");
CREATE INDEX "dciangxkox_dzih_sieux_yonh_id_b5ac81b0" ON "dciangxkox_dzih" ("sieux_yonh_id");
CREATE INDEX "dciangxkox_dzih_cjeng_id_313dbc70" ON "dciangxkox_dzih" ("cjeng_id");
CREATE INDEX "dciangxkox_dzih_yonh_id_72ba2f0e" ON "dciangxkox_dzih" ("yonh_id");
CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
